openapi: 3.0.0
info:
  title: Event Store
  description: |
    Best event store API.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /events/{event_type}:
    post:
      summary: Save event
      parameters:
        - name: event_type
          in: path
          required: true
          description: Identifier of the event type.
          schema:
            type : string
          example: 577B4ADB-FCB6-43A5-845B-918A952CB9B4
      
      requestBody:
        required: true
        content:
          application/json:
            example: [
              {
                event_id: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A,
                quantity: 4,
                customizations: {
                    color: 'blue',
                    sizeObj: {
                      type: 'W',
                      value: 10
                    }
                  }
              },
              {
                event_id: 181BBDA8-030E-407A-8DC4-7F16A05F55FF,
                quantity: 6,
                customizations: {
                    size: 4
                  }
              }
            ]
            schema:
              type: array
              items:
                type: object
                properties:
                  product_id:
                    type: string
                    example: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A
                  quantity:
                    type: integer
                    minimum: 1
                    maximum: 12
                    example: 2
                  customizations:
                    type: object
                    example: {
                      color: 'blue',
                      sizeObj: {
                        type: 'W',
                        value: 10
                      }
                    }
                
                  
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
